# Generated by Django 2.2 on 2019-05-10 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('institutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnames', models.CharField(max_length=100)),
                ('names', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.Institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('publications', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.Publication')),
                ('researchers', models.ManyToManyField(related_name='investigation', to='directory.Researcher')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsability', to='directory.Researcher')),
            ],
        ),
    ]
