# Generated by Django 2.2 on 2019-05-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20190525_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.Project'),
        ),
    ]
