# Generated by Django 2.2 on 2019-05-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20190525_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
