# Generated by Django 2.2 on 2019-06-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20190607_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='institute',
        ),
        migrations.AddField(
            model_name='researcher',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='document',
            field=models.FileField(upload_to='static/publicaciones'),
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.AddField(
            model_name='researcher',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.Institution'),
        ),
    ]
