# Generated by Django 2.2 on 2019-06-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20190613_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/default.png', upload_to='media/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='document',
            field=models.FileField(upload_to='media/publicaciones'),
        ),
    ]
