# Generated by Django 2.2 on 2019-06-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20190613_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='education',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='experience',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/default.png', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='skills',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
