# Generated by Django 2.2 on 2019-06-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_auto_20190613_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.Institution'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures'),
        ),
    ]
