# Generated by Django 2.2 on 2019-06-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_remove_researcher_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='researchers',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='author',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorPublication', to='directory.Publication'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projectMember', to='directory.Researcher'),
        ),
        migrations.AlterField(
            model_name='author',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorResearcher', to='directory.Researcher'),
        ),
        migrations.AlterField(
            model_name='project',
            name='background',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projectResponsible', to='directory.Researcher'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publicationProject', to='directory.Project'),
        ),
    ]
