# Generated by Django 2.2 on 2019-06-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_auto_20190615_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='publicationAuthor', through='directory.Author', to='directory.Researcher'),
        ),
    ]
