# Generated by Django 2.2 on 2019-06-15 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_publication_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorPublication', to='directory.Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='publicationProject', to='directory.Project'),
        ),
    ]
